"""salve

Revision ID: 955fc3268ebd
Revises: c006e8463eb4
Create Date: 2024-07-10 07:52:19.961217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955fc3268ebd'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
